/*
 * SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_ZYNQ_XADC_PS_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_ZYNQ_XADC_PS_H_

#include <zephyr/drivers/sensor.h>

/** Zynq internal sensors, in degrees Celsius or volts. Extrema since XADC reset. */
enum sensor_channel_zynq_xadc {
	SENSOR_CHAN_ZYNQ_XADC_TEMP = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_ZYNQ_XADC_VCCINT,
	SENSOR_CHAN_ZYNQ_XADC_VCCAUX,
	SENSOR_CHAN_ZYNQ_XADC_VCCBRAM,
	SENSOR_CHAN_ZYNQ_XADC_VCCPINT,
	SENSOR_CHAN_ZYNQ_XADC_VCCPAUX,
	SENSOR_CHAN_ZYNQ_XADC_VCCO_DDR,
	SENSOR_CHAN_ZYNQ_XADC_TEMP_MAX,
	SENSOR_CHAN_ZYNQ_XADC_VCCINT_MAX,
	SENSOR_CHAN_ZYNQ_XADC_VCCAUX_MAX,
	SENSOR_CHAN_ZYNQ_XADC_VCCBRAM_MAX,
	SENSOR_CHAN_ZYNQ_XADC_VCCPINT_MAX,
	SENSOR_CHAN_ZYNQ_XADC_VCCPAUX_MAX,
	SENSOR_CHAN_ZYNQ_XADC_VCCO_DDR_MAX,
	SENSOR_CHAN_ZYNQ_XADC_TEMP_MIN,
	SENSOR_CHAN_ZYNQ_XADC_VCCINT_MIN,
	SENSOR_CHAN_ZYNQ_XADC_VCCAUX_MIN,
	SENSOR_CHAN_ZYNQ_XADC_VCCBRAM_MIN,
	SENSOR_CHAN_ZYNQ_XADC_VCCPINT_MIN,
	SENSOR_CHAN_ZYNQ_XADC_VCCPAUX_MIN,
	SENSOR_CHAN_ZYNQ_XADC_VCCO_DDR_MIN,
};

#endif
